services:
  - type: web
    name: quan-ly-kho-server
    env: node
    region: singapore
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    healthCheckPath: /health
    pullRequestPreviewsEnabled: false
    envVars:
      - key: NODE_VERSION
        value: 18
